# Introduction to Numpy

Python has different libraries for different type of tasks that you need, we are exploring Numpy, a library that includes comprehensive   mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

Numpy allows us to create and manipulate matrices easily.



## Importing and Creating a matrix

To start you will import numpy and create a matrices as below

In [5]:
import numpy as np

# Create a matrices (1 x 3)

arr = np.array([1,3,4])
print(arr)

[1 3 4]


To get the dimension of a matrices, we will use the shape method and call it on the matrices.

In [6]:
print(arr.shape)

(3,)


We will create a matrices of size 2 x 3 as below 

In [7]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


Now you will create another matrice of type 3 x 3 that will contains, [1,2,3], [4,5,6] and [7,8,9]

## Accessing data from Numpy

Just like list in Python index in numpy array starts with index 0.. If you try to get the value $a_{22}$ from the matrices, you have to minus 1 in each of the index and call it in a []. For example the below code is to get the value $a_{22}$ which is 5 

In [9]:
val = arr[1][1]
print(val)

5


Get the value of the following matrices

1. $a_{11}$ 
2. $a_{20}$ 
3. $a_{21}$ 


To get the entire row or column of a matrix, you will use : in the array.

In [11]:
b = np.array([[1,-2,5],[-3,2,9]])

print("first row")
print(b[0,:])
print("second row")
print(b[1,:])

first row
[ 1 -2  5]
second row
[-3  2  9]


Similarly you can use : to get all value in the first , second or third column


In [12]:
print(b[:,0])
print(b[:,1])
print(b[:,2])

[ 1 -3]
[-2  2]
[5 9]


## Matrix Operation

### Addition

Just like normal addition operation, you use **+** operator to sum two matrices

In [14]:
a = np.array([[6],[-2]])
b = np.array([[-5],[1]])
tambah = a + b
print(tambah)

[[ 1]
 [-1]]


## Substraction

Just like normal addition operation, you use **-** operator to substract/minus two matrices

In [16]:
a = np.array([[1,-2,4]])
b = np.array([[2,1,3]])
minus1 = a - b
print(minus1)


[[-1 -3  1]]


### Exercise:


1. Create two matrices:

[[8,-1],[-5,1]] and [[1,3],[3,-4]] and find the sum of these two matrices

2. Create three matrices

a = [[3],[1]], b = [[-4],[4]], c = [[2],[-2]]

Find the result for  a + b - c programatically

## Scalar Multiplication

We use * to perform scalar multiplication

In [21]:
c = np.array([[2,-1],[-5,7]])
print(c)

[[ 2 -1]
 [-5  7]]


In [22]:


c_multi = 3 * c 
print(c_multi)


[[  6  -3]
 [-15  21]]


In [23]:
c_multi2 = 1/6 * c
print(c_multi2)

[[ 0.33333333 -0.16666667]
 [-0.83333333  1.16666667]]


## Vector multiplication

To perform vector multiplication in numpy, you will use the function .dot

In [24]:
a1 = np.array([[1,2]])
print(a1)



[[1 2]]


In [25]:
a2 = np.array([[3],[4]])
print(a2)


[[3]
 [4]]


In [26]:
va1_a2 = a1.dot(a2)
print(va1_a2)

[[11]]


## Exercise Mutiplication

1. Perform vector multiplication for the following matrices:
A = [[-2,0],[3,5]]
A = [[1],[0]

2. Given the following matrices
A = [[-3,0],[2,1]]

Find the result and formula in numpy for $A^{2}$ + 4A

## Transpose Matrix

In class, you have seen transpose matrix $A^{T}$ . In numpy , you can get directly matric transpose by using the method **T**

In [27]:
b = np.array([[-1,3,7],[2,4,1],[3,5,2]])
bt = b.T
print(bt)

[[-1  2  3]
 [ 3  4  5]
 [ 7  1  2]]


In [ ]:
## TODO Add exercise to test students' comprehension

## Determinant of a Matrix

To get a determinant of a Matrix  |A|, you will use a method from numpy which is called dt.

In [29]:
a = np.array([[2,4],[-2,-3]])
b = np.array([[1,1],[3,6]])
deta = round(np.linalg.det(a))
detb = round(np.linalg.det(b))
print(deta)
print(detb)

2
3


### Exercise

Use the formula that you have learned and show that |A||B| = |AB| using numpy

## Minor of a matrix

Numpy does not have a built in minor function, you will have to create and use the following method right away

In [30]:
def minorOfAMatrix(A,i,j):
	rowOperation = np.delete(A,i,0)
	columnOperation = np.delete(rowOperation,j,1)
	return columnOperation

In [32]:
matrix = np.array([[1,1,1],[0,1,1],[0,0,1]])
minor1 = minorOfAMatrix(matrix,0,0)
print(minor1)

[[1 1]
 [0 1]]


## Eye of a matrix

To create eye of a matrix, call directly the function eye that will create an eye of the matrix based on dimension given in parameters

In [33]:
a = np.eye(1)
b = np.eye(2)
c = np.eye(3)
print(a)
print(b)
print(c)

[[1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Matrix Inverse

To get the Inverse of a Matrix A, $A^{-1}$, you will use the function inv from numpy. 

In [35]:
a = np.array([[3,1],[0,-1]])
rev_a = np.linalg.inv(a)
print(rev_a)


[[ 0.33333333  0.33333333]
 [-0.         -1.        ]]


## Solving a linear algebra equation

As you have seen and proved in class, you can solve a Linear Algebra Equation using the following formula:

X = $A^{-1}$B

Based on what you have seen previously, find the correct methods from numpy to create and solve the following linear algebra equation:

*x+2y+z=1* <br>
*x+3y=2* <br>
*-y+8z=3* <br>

In [ ]:
#Todo add additional exercise if you want

Numpy also provides a solve method that can easily solves a linear algebra equation, as below, once you have declared A and B

In [36]:
X2 = np.linalg.solve(A,B)

NameError: name 'A' is not defined